/**
 * Unified job data — single source of truth for all job listings.
 * Mocks use real mockId references (integers matching MOCKS[].id).
 * Candidates are derived from candidates.js — no topCandidates duplication.
 */

export const JOBS = [
  {
    id: 1,
    title: 'Senior Software Engineer',
    department: 'Engineering',
    seniority: 'Senior',
    jobType: 'Full-time',
    status: 'active',
    location: 'San Francisco, CA',
    locationType: 'Hybrid',
    description:
      'We are looking for a Senior Software Engineer to build scalable backend services and collaborate with cross-functional teams.',
    duration: '5d 4h',
    publishDate: 'Jan 15, 2026',
    endDate: 'Jun 1, 2026',
    maxCandidates: 150,
    totalApplied: 142,
    shortlisted: 23,
    accepted: 8,
    rejected: 64,
    pending: 47,
    avgScore: 79,
    passRate: 54,
    activeDays: 45,
    skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Microservices', 'Docker'],
    mocks: [
      {
        id: 4,
        name: 'Database Design',
        weight: 25,
        duration: '40 min',
        durationMin: 40,
        avgScore: 71,
        passRate: 58,
      },
      {
        id: 1,
        name: 'System Design',
        weight: 30,
        duration: '45 min',
        durationMin: 45,
        avgScore: 68,
        passRate: 49,
      },
      {
        id: 3,
        name: 'Behavioral',
        weight: 15,
        duration: '30 min',
        durationMin: 30,
        avgScore: 84,
        passRate: 76,
      },
      {
        id: 2,
        name: 'Coding Challenge',
        weight: 30,
        duration: '60 min',
        durationMin: 60,
        avgScore: 72,
        passRate: 55,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 3 },
      { label: 'Feb 16', value: 5 },
      { label: 'Feb 17', value: 8 },
      { label: 'Feb 18', value: 12 },
      { label: 'Feb 19', value: 7 },
      { label: 'Feb 20', value: 15 },
      { label: 'Feb 21', value: 9 },
      { label: 'Feb 22', value: 11 },
      { label: 'Feb 23', value: 18 },
      { label: 'Feb 24', value: 6 },
      { label: 'Feb 25', value: 9 },
      { label: 'Feb 26', value: 14 },
      { label: 'Feb 27', value: 8 },
      { label: 'Feb 28', value: 11 },
    ],
  },
  {
    id: 2,
    title: 'Frontend Developer',
    department: 'Engineering',
    seniority: 'Mid',
    jobType: 'Full-time',
    status: 'active',
    location: 'New York, NY',
    locationType: 'Remote',
    description:
      'Join our frontend team to build modern, accessible web applications using React and TypeScript.',
    duration: '12d 8h',
    publishDate: 'Jan 20, 2026',
    endDate: 'Jul 1, 2026',
    maxCandidates: 100,
    totalApplied: 89,
    shortlisted: 15,
    accepted: 5,
    rejected: 32,
    pending: 37,
    avgScore: 82,
    passRate: 61,
    activeDays: 40,
    skills: ['React', 'TypeScript', 'CSS', 'Vite'],
    mocks: [
      {
        id: 6,
        name: 'React Challenge',
        weight: 40,
        duration: '50 min',
        durationMin: 50,
        avgScore: 80,
        passRate: 65,
      },
      {
        id: 7,
        name: 'CSS Architecture',
        weight: 30,
        duration: '30 min',
        durationMin: 30,
        avgScore: 78,
        passRate: 58,
      },
      {
        id: 1,
        name: 'System Design',
        weight: 30,
        duration: '45 min',
        durationMin: 45,
        avgScore: 74,
        passRate: 50,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 2 },
      { label: 'Feb 16', value: 7 },
      { label: 'Feb 17', value: 4 },
      { label: 'Feb 18', value: 9 },
      { label: 'Feb 19', value: 6 },
      { label: 'Feb 20', value: 11 },
      { label: 'Feb 21', value: 8 },
      { label: 'Feb 22', value: 5 },
      { label: 'Feb 23', value: 13 },
      { label: 'Feb 24', value: 7 },
      { label: 'Feb 25', value: 10 },
      { label: 'Feb 26', value: 6 },
      { label: 'Feb 27', value: 12 },
      { label: 'Feb 28', value: 9 },
    ],
  },
  {
    id: 3,
    title: 'UX Designer',
    department: 'Design',
    seniority: 'Mid',
    jobType: 'Full-time',
    status: 'scheduled',
    location: 'Austin, TX',
    locationType: 'On-site',
    description:
      'We need a creative UX Designer to craft intuitive user experiences across our product suite.',
    duration: '3d 6h',
    publishDate: 'Feb 1, 2026',
    endDate: 'Aug 1, 2026',
    maxCandidates: 80,
    totalApplied: 56,
    shortlisted: 10,
    accepted: 3,
    rejected: 18,
    pending: 25,
    avgScore: 71,
    passRate: 48,
    activeDays: 28,
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    mocks: [
      {
        id: 8,
        name: 'Portfolio Review',
        weight: 40,
        duration: '25 min',
        durationMin: 25,
        avgScore: 74,
        passRate: 52,
      },
      {
        id: 13,
        name: 'Design Challenge',
        weight: 40,
        duration: '45 min',
        durationMin: 45,
        avgScore: 69,
        passRate: 44,
      },
      {
        id: 3,
        name: 'Behavioral',
        weight: 20,
        duration: '30 min',
        durationMin: 30,
        avgScore: 78,
        passRate: 60,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 1 },
      { label: 'Feb 16', value: 3 },
      { label: 'Feb 17', value: 5 },
      { label: 'Feb 18', value: 4 },
      { label: 'Feb 19', value: 7 },
      { label: 'Feb 20', value: 6 },
      { label: 'Feb 21', value: 2 },
      { label: 'Feb 22', value: 8 },
      { label: 'Feb 23', value: 5 },
      { label: 'Feb 24', value: 3 },
      { label: 'Feb 25', value: 6 },
      { label: 'Feb 26', value: 4 },
      { label: 'Feb 27', value: 7 },
      { label: 'Feb 28', value: 5 },
    ],
  },
  {
    id: 4,
    title: 'Data Analyst',
    department: 'Data',
    seniority: 'Junior',
    jobType: 'Full-time',
    status: 'active',
    location: 'Chicago, IL',
    locationType: 'Hybrid',
    description:
      'Seeking a Data Analyst to help translate data into actionable insights for our product and growth teams.',
    duration: '8d 11h',
    publishDate: 'Jan 10, 2026',
    endDate: 'May 15, 2026',
    maxCandidates: 120,
    totalApplied: 73,
    shortlisted: 12,
    accepted: 4,
    rejected: 28,
    pending: 29,
    avgScore: 69,
    passRate: 42,
    activeDays: 52,
    skills: ['SQL', 'Python', 'Tableau', 'Excel', 'Data Modeling'],
    mocks: [
      {
        id: 10,
        name: 'SQL Assessment',
        weight: 35,
        duration: '40 min',
        durationMin: 40,
        avgScore: 65,
        passRate: 40,
      },
      {
        id: 14,
        name: 'Data Modeling',
        weight: 35,
        duration: '40 min',
        durationMin: 40,
        avgScore: 70,
        passRate: 45,
      },
      {
        id: 9,
        name: 'Case Study',
        weight: 30,
        duration: '60 min',
        durationMin: 60,
        avgScore: 72,
        passRate: 48,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 4 },
      { label: 'Feb 16', value: 6 },
      { label: 'Feb 17', value: 3 },
      { label: 'Feb 18', value: 8 },
      { label: 'Feb 19', value: 5 },
      { label: 'Feb 20', value: 10 },
      { label: 'Feb 21', value: 7 },
      { label: 'Feb 22', value: 4 },
      { label: 'Feb 23', value: 9 },
      { label: 'Feb 24', value: 6 },
      { label: 'Feb 25', value: 5 },
      { label: 'Feb 26', value: 11 },
      { label: 'Feb 27', value: 3 },
      { label: 'Feb 28', value: 7 },
    ],
  },
  {
    id: 5,
    title: 'Backend Engineer',
    department: 'Engineering',
    seniority: 'Senior',
    jobType: 'Full-time',
    status: 'closed',
    location: 'Seattle, WA',
    locationType: 'Remote',
    description:
      'We were looking for a Backend Engineer to design and maintain our API platform and data pipelines.',
    duration: '4d 2h',
    publishDate: 'Nov 1, 2025',
    endDate: 'Feb 1, 2026',
    maxCandidates: 200,
    totalApplied: 210,
    shortlisted: 35,
    accepted: 12,
    rejected: 100,
    pending: 63,
    avgScore: 85,
    passRate: 62,
    activeDays: 92,
    skills: ['Node.js', 'Go', 'REST APIs', 'MongoDB', 'Redis', 'Kubernetes'],
    mocks: [
      {
        id: 1,
        name: 'System Design',
        weight: 30,
        duration: '45 min',
        durationMin: 45,
        avgScore: 82,
        passRate: 60,
      },
      {
        id: 2,
        name: 'Coding Challenge',
        weight: 30,
        duration: '60 min',
        durationMin: 60,
        avgScore: 88,
        passRate: 68,
      },
      {
        id: 5,
        name: 'API Design',
        weight: 25,
        duration: '35 min',
        durationMin: 35,
        avgScore: 84,
        passRate: 58,
      },
      {
        id: 3,
        name: 'Behavioral',
        weight: 15,
        duration: '30 min',
        durationMin: 30,
        avgScore: 90,
        passRate: 78,
      },
    ],
    applicationTrend: [
      { label: 'Dec 1', value: 8 },
      { label: 'Dec 8', value: 14 },
      { label: 'Dec 15', value: 18 },
      { label: 'Dec 22', value: 12 },
      { label: 'Dec 29', value: 20 },
      { label: 'Jan 5', value: 25 },
      { label: 'Jan 12', value: 22 },
      { label: 'Jan 19', value: 16 },
      { label: 'Jan 26', value: 10 },
    ],
  },
  {
    id: 6,
    title: 'Product Manager',
    department: 'Product',
    seniority: 'Senior',
    jobType: 'Full-time',
    status: 'active',
    location: 'Los Angeles, CA',
    locationType: 'Hybrid',
    description:
      'Lead product strategy and roadmapping for our core SaaS platform, collaborating with engineering and design.',
    duration: '2d 8h',
    publishDate: 'Feb 10, 2026',
    endDate: 'Jul 15, 2026',
    maxCandidates: 80,
    totalApplied: 64,
    shortlisted: 8,
    accepted: 2,
    rejected: 22,
    pending: 32,
    avgScore: 76,
    passRate: 50,
    activeDays: 20,
    skills: ['Roadmapping', 'Agile', 'Analytics', 'Stakeholder Mgmt'],
    mocks: [
      {
        id: 9,
        name: 'Case Study',
        weight: 40,
        duration: '60 min',
        durationMin: 60,
        avgScore: 75,
        passRate: 48,
      },
      {
        id: 3,
        name: 'Behavioral',
        weight: 30,
        duration: '30 min',
        durationMin: 30,
        avgScore: 80,
        passRate: 56,
      },
      {
        id: 15,
        name: 'Strategy Assessment',
        weight: 30,
        duration: '45 min',
        durationMin: 45,
        avgScore: 72,
        passRate: 44,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 5 },
      { label: 'Feb 16', value: 3 },
      { label: 'Feb 17', value: 7 },
      { label: 'Feb 18', value: 6 },
      { label: 'Feb 19', value: 9 },
      { label: 'Feb 20', value: 4 },
      { label: 'Feb 21', value: 8 },
      { label: 'Feb 22', value: 6 },
      { label: 'Feb 23', value: 10 },
      { label: 'Feb 24', value: 5 },
      { label: 'Feb 25', value: 7 },
      { label: 'Feb 26', value: 3 },
      { label: 'Feb 27', value: 9 },
      { label: 'Feb 28', value: 6 },
    ],
  },
  {
    id: 7,
    title: 'DevOps Engineer',
    department: 'Infrastructure',
    seniority: 'Mid',
    jobType: 'Full-time',
    status: 'scheduled',
    location: 'Denver, CO',
    locationType: 'Remote',
    description:
      'Automate and manage our cloud infrastructure, CI/CD pipelines, and monitoring systems.',
    duration: '7d 12h',
    publishDate: 'Mar 1, 2026',
    endDate: 'Sep 1, 2026',
    maxCandidates: 60,
    totalApplied: 38,
    shortlisted: 6,
    accepted: 1,
    rejected: 12,
    pending: 19,
    avgScore: 81,
    passRate: 55,
    activeDays: 0,
    skills: ['AWS', 'Terraform', 'Docker', 'CI/CD', 'Linux'],
    mocks: [
      {
        id: 11,
        name: 'CI/CD Pipeline',
        weight: 35,
        duration: '40 min',
        durationMin: 40,
        avgScore: 80,
        passRate: 55,
      },
      {
        id: 12,
        name: 'Cloud Architecture',
        weight: 35,
        duration: '50 min',
        durationMin: 50,
        avgScore: 78,
        passRate: 50,
      },
      {
        id: 16,
        name: 'Monitoring Setup',
        weight: 30,
        duration: '35 min',
        durationMin: 35,
        avgScore: 82,
        passRate: 58,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 2 },
      { label: 'Feb 16', value: 4 },
      { label: 'Feb 17', value: 3 },
      { label: 'Feb 18', value: 5 },
      { label: 'Feb 19', value: 2 },
      { label: 'Feb 20', value: 6 },
      { label: 'Feb 21', value: 4 },
      { label: 'Feb 22', value: 3 },
      { label: 'Feb 23', value: 7 },
      { label: 'Feb 24', value: 2 },
      { label: 'Feb 25', value: 5 },
      { label: 'Feb 26', value: 3 },
      { label: 'Feb 27', value: 4 },
      { label: 'Feb 28', value: 6 },
    ],
  },
  {
    id: 8,
    title: 'ML Engineer',
    department: 'Data',
    seniority: 'Senior',
    jobType: 'Full-time',
    status: 'active',
    location: 'Boston, MA',
    locationType: 'Hybrid',
    description:
      'Design and deploy machine learning models at scale for our recommendation and search systems.',
    duration: '15d 6h',
    publishDate: 'Jan 5, 2026',
    endDate: 'Jun 15, 2026',
    maxCandidates: 50,
    totalApplied: 45,
    shortlisted: 9,
    accepted: 3,
    rejected: 15,
    pending: 18,
    avgScore: 89,
    passRate: 67,
    activeDays: 56,
    skills: ['Python', 'PyTorch', 'TensorFlow', 'MLOps', 'Statistics'],
    mocks: [
      {
        id: 17,
        name: 'Model Design',
        weight: 35,
        duration: '50 min',
        durationMin: 50,
        avgScore: 88,
        passRate: 65,
      },
      {
        id: 18,
        name: 'Python Challenge',
        weight: 25,
        duration: '45 min',
        durationMin: 45,
        avgScore: 92,
        passRate: 72,
      },
      {
        id: 1,
        name: 'System Design',
        weight: 25,
        duration: '45 min',
        durationMin: 45,
        avgScore: 85,
        passRate: 60,
      },
      {
        id: 19,
        name: 'Paper Review',
        weight: 15,
        duration: '30 min',
        durationMin: 30,
        avgScore: 90,
        passRate: 70,
      },
    ],
    applicationTrend: [
      { label: 'Feb 15', value: 1 },
      { label: 'Feb 16', value: 3 },
      { label: 'Feb 17', value: 2 },
      { label: 'Feb 18', value: 5 },
      { label: 'Feb 19', value: 3 },
      { label: 'Feb 20', value: 4 },
      { label: 'Feb 21', value: 6 },
      { label: 'Feb 22', value: 2 },
      { label: 'Feb 23', value: 5 },
      { label: 'Feb 24', value: 3 },
      { label: 'Feb 25', value: 7 },
      { label: 'Feb 26', value: 4 },
      { label: 'Feb 27', value: 3 },
      { label: 'Feb 28', value: 5 },
    ],
  },
];

/* -------------------------------------------------
   Query helpers
   ------------------------------------------------- */

export function getJobById(id) {
  return JOBS.find((j) => j.id === id) ?? null;
}

/* -------------------------------------------------
   CRUD helpers (simulated)
   ------------------------------------------------- */

export function updateJob(id, patch) {
  const idx = JOBS.findIndex((j) => j.id === id);
  if (idx === -1) return null;
  JOBS[idx] = { ...JOBS[idx], ...patch };
  return JOBS[idx];
}

export function addJob(data) {
  const maxId = JOBS.reduce((m, j) => Math.max(m, j.id), 0);
  const newJob = {
    id: maxId + 1,
    totalApplied: 0,
    shortlisted: 0,
    accepted: 0,
    rejected: 0,
    pending: 0,
    avgScore: 0,
    passRate: 0,
    activeDays: 0,
    applicationTrend: [],
    ...data,
  };
  JOBS.push(newJob);
  return newJob;
}

export function removeJob(id) {
  const idx = JOBS.findIndex((j) => j.id === id);
  if (idx === -1) return false;
  JOBS.splice(idx, 1);
  return true;
}

export function duplicateJob(id) {
  const source = getJobById(id);
  if (!source) return null;
  const { id: _id, ...rest } = source;
  return addJob({
    ...rest,
    title: `${rest.title} (Copy)`,
    status: rest.status === 'scheduled' ? 'scheduled' : 'active',
    totalApplied: 0,
    shortlisted: 0,
    accepted: 0,
    rejected: 0,
    pending: 0,
    avgScore: 0,
    passRate: 0,
    activeDays: 0,
    applicationTrend: [],
  });
}
